server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: back-osck-connector
  main:
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  enable-native-support: 'true'

application:
  request:
    mappings: /osck-connector

oauth:
  base-url: ${OAUTH_BASE_URL:http://172.18.1.192:8280/osck/oauth/}

osck:
  url: ${OSCK_URL_SERVICES:http://172.18.1.192:8280/osck/oauth/consume/}